[package]
edition = "2021"
name = "slip"
version = "0.1.0"

[dependencies]
clap = { version = "3.0.0", features = ["derive"] }
toml = "0.5"
serde_derive = "1.0.133"
serde = "1.0.133"
shellexpand = "2.1.0"
url = "2.2.1"
